# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Use Tag as Version
      id: get_version
      run: |
        # The tag name (e.g., v1.0.0) is available in the GitHub context
        VERSION=${{ github.event.release.tag_name }}
          
        # Optional: Remove a common prefix like 'v' if needed (e.g., v1.0.0 -> 1.0.0)
        # VERSION_NUMBER="${VERSION#v}" 
          
        # Set the version as an output variable for use in later steps
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Restore dependencies
      working-directory: Nuget.BoilerPlate
      run: dotnet restore
    - name: Pack
      working-directory: Nuget.BoilerPlate
      run: dotnet pack -c Release /p:Version=${{ steps.get_version.outputs.VERSION }} --no-restore
    - name: Publish
      working-directory: Nuget.BoilerPlate
      run:  dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"
